version: 0.2

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Test started on `date`
      - mvn clean compile test
  build:
    commands:
      - echo check what is there at the beginning `pwd`
      - echo check what is there at the beginning `ls`
      - echo Build started on `date`
#      - mvn package shade:shade
#      - mv target/HelloWorld-1.0.jar .
#      - unzip -o HelloWorld-1.0.jar
#      - rm -rf target tst src buildspec.yml pom.xml HelloWorld-1.0.jar
#      - echo check what is left `ls`
      - aws cloudformation package --template template.yml --s3-bucket stsai-codestart-codebuild-s3 --output-template template-export.yml
      - echo check what is left after package `ls`
      - echo check what is left after package `cat template-export.yml`
artifacts:
  files:
    - template-export.yml